import { Inter } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "AnimationProductCard",
  description: "Generated by ksabrineh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen">{children}</body>
    </html>
  );
}
